#!/bin/bash

if [ $1 == "configure" ]; then

	update-rc.d headphones defaults &>/dev/null

	if [ ! -d "/home/xbian/downloads" ]; then
		mkdir -p /home/xbian/downloads
	fi

	chmod 777 /home/xbian/downloads
	chown xbian:xbian /home/xbian/downloads

	if [ ! -d "/home/xbian/incomplete" ]; then
		mkdir -p /home/xbian/incomplete
	fi

	chmod 777 /home/xbian/incomplete
	chown xbian:xbian /home/xbian/incomplete

	if [ ! -d "/home/xbian/torrents" ]; then
		mkdir -p /home/xbian/torrents
	fi

	chmod 777 /home/xbian/torrents
	chown xbian:xbian /home/xbian/torrents


	chmod 777 /usr/local/share/headphones
	chown -R xbian /usr/local/share/headphones
	chmod -R 777 /etc/headphones


	/etc/init.d/headphones start &>/dev/null

fi
